# Generated by Django 5.0 on 2025-10-07 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Notification Name')),
                ('advertisement_ref_no', models.CharField(blank=True, default='', max_length=100)),
                ('job_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(blank=True, choices=[('railway', 'Railway'), ('police', 'Police'), ('banking', 'Banking'), ('andhra_pradesh', 'Andhra Pradesh')], default='', max_length=50)),
                ('total_vacancies', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('admit_release_date', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('extended_date', models.TextField(blank=True, default='')),
                ('fee_general', models.CharField(blank=True, default='', max_length=80)),
                ('fee_obc', models.CharField(blank=True, default='', max_length=80)),
                ('fee_sc', models.CharField(blank=True, default='', max_length=80)),
                ('fee_st', models.CharField(blank=True, default='', max_length=80)),
                ('fee_ews', models.CharField(blank=True, default='', max_length=80)),
                ('fee_female', models.CharField(blank=True, default='', max_length=80)),
                ('fee_ex_serviceman', models.CharField(blank=True, default='', max_length=80)),
                ('fee_ph', models.CharField(blank=True, default='', max_length=80)),
                ('fee_other', models.CharField(blank=True, default='', max_length=80)),
                ('dob_from', models.TextField(blank=True, default='')),
                ('dob_to', models.TextField(blank=True, default='')),
                ('age_relaxation', models.TextField(blank=True, default='')),
                ('qualification', models.TextField(blank=True, default='')),
                ('apply_online_link', models.URLField(blank=True, default='')),
                ('admit_card_link', models.URLField(blank=True, default='')),
                ('notification_pdf_link', models.URLField(blank=True, default='')),
                ('official_website', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('vacancy_number', models.IntegerField(blank=True, null=True)),
                ('job_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_details', to='jobs.jobnotification')),
            ],
        ),
    ]
