# Generated by Django 5.0 on 2026-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnotification',
            name='admit_card_link',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='admit_release_date',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='age_relaxation',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='dob_from',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='dob_to',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='extended_date',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_ews',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_ex_serviceman',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_female',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_general',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_obc',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_other',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_ph',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_sc',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='fee_st',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='notification_pdf_link',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='official_website',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='result_date',
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
