# Generated by Django 5.0 on 2026-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobnotification_admit_card_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='custom_field',
            field=models.TextField(blank=True, default='', help_text='Extra notes / salary / age limit / selection process / anything'),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='notification_pdf_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='official_website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
