# Generated by Django 5.0 on 2025-09-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_experience_level_job_location_alter_job_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Mid', 'Mid Level'), ('Senior', 'Senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
