# Generated by Django 5.0 on 2026-05-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobnotification_custom_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnotification',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='jobnotification',
            name='job_uid',
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('job_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='jobs.jobnotification')),
            ],
        ),
    ]
