# Generated by Django 5.0 on 2026-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobnotification_custom_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='admit_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
