# Generated by Django 5.0 on 2026-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobnotification_admit_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='dob_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='dob_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
