# Generated by Django 5.0 on 2026-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobnotification_dob_from_jobnotification_dob_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotification',
            name='dob_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='dob_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
