# Generated by Django 5.0 on 2026-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobnotification_dob_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='admit_card_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
